### ISSUE TITLE
Invalid 'group': 'SmartTab' on startup 

### ISSUE THREAD

**Issue by maxmahlke** [boltlessengineer/smart-tab.nvim#1]
Hi, I tried installing the plugin with `lazy` by putting a file with the following contents in my `nvim/lua/plugins/` path (sourced by `lazy`):

```
return {
  "boltlessengineer/smart-tab.nvim",
  opts = {
    skips = { "string_content" },
    mapping = "<tab>",
  },
}
```

The plugin is then installed correctly but when re-opening neovim to source the plugin code I get the following error:

```
Error  02:51:36 PM notify.error lazy.nvim Failed to run `config` for smart-tab.nvim

.../.local/share/nvim/lazy/smart-tab.nvim/lua/smart-tab.lua:49: Invalid 'group': 'SmartTab'

# stacktrace:
  - /smart-tab.nvim/lua/smart-tab.lua:49 _in_ **setup**
  - .config/nvim/lua/config/lazy.lua:9
  - dots/nvim/init.lua:2
```

This seems to be related to this autogroup command:

https://github.com/boltlessengineer/smart-tab.nvim/blob/374b712077ae8584f3548f32ec5b705f2bc2c91f/lua/smart-tab.lua#L49

I'm running `NVIM v0.9.1`.

**Comment by boltlessengineer** [comment]
Fixed. Sorry about that bug.
